[book]
authors = ["hanwei"]
#language = "en"
language = "zh-CN"
multilingual = false
src = "src"
title = "Bazel在企业项目中的应用"

[output.html]
additional-css = ["style.css"]
additional-js = ["sidebar.js"]


# [output.pdf]